In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.permutation(3)

array([1, 0, 2])

In [22]:
one=np.array([0.03856422, 0.  ,       0.  ,       0.  ,       0.02908806, 0.60474418,
 0.00078264, 0.10473383, 0.,         0.,         0.02188159, 0.,
 0.20020548])

In [25]:
np.argsort(one)

array([ 1,  2,  3,  8,  9, 11,  6, 10,  4,  0,  7, 12,  5], dtype=int64)

In [24]:
np.flipud(np.argsort(one))

array([ 5, 12,  7,  0,  4, 10,  6, 11,  9,  8,  3,  2,  1], dtype=int64)

In [19]:
np.arange(7)+0.5

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5])